global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rpc-gateway'
    static_configs:
      - targets: ['rpc-gateway:8000']

  - job_name: 'static-gateway'
    static_configs:
      - targets: [ 'static-gateway:8001' ]

  - job_name: 'to-upper'
    static_configs:
      - targets: ['to-upper:8000']

  - job_name: 'to-lower'
    static_configs:
      - targets: ['to-lower:8000']
